name: 4 | Deploy prod
on:
  push:
    branches:
      - 'releases/prod'

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    environment:
      name: deploy/prod
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn build

      - name: Bump and tag
        id: github-tag-action
        uses: mathieudutour/github-tag-action@d745f2e74aaf1ee82e747b181f7a0967978abee0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: releases/prod
          default_bump: patch

      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/$IMAGE_TAG

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_TAG $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
